a = float(input("Enter the 1st number: "))
b = float(input("Enter the 2nd number: "))
c = float(input("Enter the 3rd number: "))
print("a,b,c = %d, %d, %d" % (a,b,c))
print("The average of three integers = %.2f" % ((a+b+c) / 3))
print("The summation of three integers = %.2f" % (a+b+c))
print("The multiplication of three integers = %.2f" % (a*b*c))